# maintainer -*-Makefile-*-

LN = ln -s
RM = rm -f

# ==================== Easily regeneratable files ====================

all : vacall-i386-msvc.c

vacall-i386-msvc.c : vacall-i386-macro.S
	(echo '#ifdef _MSC_VER' ; echo '#include "vacall_r.h"' ; echo '#endif' ; sed -e '/FUNEND(callback_receiver,/q' < vacall-i386-macro.S ; cat get_receiver.c) > vacall-i386-msvc.c

totally-clean : force
	$(RM) vacall-i386-msvc.c


force :
